# Account configuration
accountConfigurationList:
  - accountName: ItachiEU # Name of your account
    accountLogin: komorowski.filip@gmail.com # Login of your account
    accountPassword: # Password of your account (optional, will be asked in a prompt if not provided)

# If enabled, seed list will be ignored and every match will be played against a random seed
randomSeed: true

# The name of the multiplayer game as it appears at the end of the url of your IDE
multiName: tic-tac-toe

# Optional. Indicates if the game is a contest or not. FALSE if not provided
isContest: false

# List of seeds to play
seedList:
  - seed=747848718
  - seed=851888179
  - seed=700073541
  - seed=683972927
  - seed=586660547
  - seed=410110611

# [0, N] forced start position at N
# -1 : Each seed is played with every starting positions configuration. (Works only with fixed seed list).
#       In 1v1, it will generate 2 games, 6 games in 1v2 and 24 games in 1v3. Best suited for non symmetrical and/or turn-based games.
# -2 : Each seed is played once, with random starting positions. Best suited for perfectly symmetrical
#       and non turn-based games in which starting position doesn't really matter, like MM, GoD, CotC, GitC, ...
playerPosition: -1

# Minimum number of enemies to play against
minEnemiesNumber: 1

# Maximum number of enemies to play against
maxEnemiesNumber: 3

# Optional. Cooldown between every game. If not provided, applying the lowest one first and adjusting it as long as CGBenchmark hits the servers' limitations.
requestCooldown: # 80 games on 1h
# requestCooldown: 72 # 150 games on 3h
# requestCooldown: 108 # 200 games on 6h
# requestCooldown: 144 # 600 games on 24h

# List of tested codes
codeConfigurationList:
  - sourcePath: C:/CGBenchmark/totest/1.cpp
    nbReplays: 1 # Number of times each seed will be played
    language: C++ # Code language
    enemies: # Enemies list. At each game, random enemies are picked from this list (their number is also picked randomly between <minEnemiesNumber> and <maxEnemiesNumber>)
      - agentId: "762230" # Enemy agentId
        name: Agade # Enemy name
      - agentId: "817482"
        name: pb4
      - agentId: "812582"
        name: reCurse
  - sourcePath: C:/CGBenchmark/totest/2.cpp
  - sourcePath: C:/CGBenchmark/totest/3.cpp

# -- The following values are the default ones that are used if not defined in the codeConfigurationList

# Default value for nbReplays
defaultNbReplays: 6

# Default value for language
defaultLanguage: C++

# Default value for enemies
defaultEnemies:
  - agentId: "123456"
    name: Recar
  - agentId: "344556"
    name: Illedan
